### ISSUE TITLE
How is the project going on?

### ISSUE THREAD

**Issue by zairl23** [enchainasia/bao_whitepaper#1]

**Comment by zhufengme** [comment]
Of course, but now our focus is on investigating market demand. Trying
to make BAO more in line with the general needs of companies or
organizations.



朱峰    Andie Zhu
---
Email: i@zhufeng.me
Twitter: http://twitter.com/zhufengme
Tel/Telegram: +16692455025
And More: http://about.me/zhufeng

**Comment by zairl23** [comment]
Roger! I am so sympathetic to your ideas in the white paper, looking forward to your great results, add oil!
